import { readFileSync, writeFileSync } from "node:fs";

const escapeHtml = value => String(value).replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#39;");
const mermaidId = value => String(value).replaceAll(/[^a-zA-Z0-9_]/g, "_");

function validate(data) {
  if (!data?.title || !Array.isArray(data.nodes) || !Array.isArray(data.edges) || !Array.isArray(data.recommendations)) throw new Error("Graph data requires title, nodes, edges, and recommendations.");
  const ids = new Set();
  for (const node of data.nodes) {
    if (!node.id || !node.label || !node.group || !node.purpose || !Array.isArray(node.evidence) || node.evidence.length === 0) throw new Error(`Node '${node.id ?? "unknown"}' requires label, group, purpose, and evidence.`);
    if (ids.has(node.id)) throw new Error(`Node '${node.id}' is duplicated.`);
    ids.add(node.id);
  }
  for (const edge of data.edges) if (!ids.has(edge.from) || !ids.has(edge.to)) throw new Error("Every edge must reference known nodes.");
  for (const flow of data.flows ?? []) if (!flow.title || !flow.summary || !Array.isArray(flow.steps) || flow.steps.some(id => !ids.has(id))) throw new Error("Every flow requires title, summary, and known node steps.");
  for (const item of data.recommendations) if (!item.title || !item.confidence || !item.why || !item.safeValidationCommand) throw new Error("Every recommendation requires title, confidence, why, and safeValidationCommand.");
}

function grouped(nodes) {
  const result = new Map();
  for (const node of nodes) result.set(node.group, [...(result.get(node.group) ?? []), node]);
  return result;
}

export function renderGraph(data) {
  validate(data);
  const graphData = JSON.stringify(data).replaceAll("<", "\\u003c");
  const groups = grouped(data.nodes);
  const groupFilters = [...groups.keys()].map(group => `<button type="button" class="filter" data-group="${escapeHtml(group)}" aria-pressed="true">${escapeHtml(group)}</button>`).join("");
  const groupMarkup = [...groups.entries()].map(([group, nodes]) => `<section class="system-group" data-group="${escapeHtml(group)}" aria-labelledby="group-${mermaidId(group)}"><header><p class="eyebrow">System</p><h3 id="group-${mermaidId(group)}">${escapeHtml(group)}</h3><span>${nodes.length} ${nodes.length === 1 ? "component" : "components"}</span></header><div class="node-stack">${nodes.map(node => `<button type="button" class="graph-node" data-node="${escapeHtml(node.id)}" aria-pressed="false"><span class="node-kind">${escapeHtml(node.kind ?? "component")}</span><strong>${escapeHtml(node.label)}</strong><span class="node-purpose">${escapeHtml(node.purpose)}</span></button>`).join("")}</div></section>`).join("\n");
  const flowMarkup = (data.flows ?? []).map(flow => `<article class="flow"><h3>${escapeHtml(flow.title)}</h3><p>${escapeHtml(flow.summary)}</p><ol>${flow.steps.map(id => `<li><button type="button" data-node-jump="${escapeHtml(id)}">${escapeHtml(data.nodes.find(node => node.id === id).label)}</button></li>`).join("")}</ol></article>`).join("") || "<p class=\"muted\">No runtime flow was established.</p>";
  const recommendations = data.recommendations.map(item => `<article class="recommendation"><div><span class="confidence">${escapeHtml(item.confidence)} confidence</span><h3>${escapeHtml(item.title)}</h3></div><p>${escapeHtml(item.why)}</p><code>${escapeHtml(item.safeValidationCommand)}</code></article>`).join("");
  const mermaid = ["flowchart LR", ...data.nodes.map(node => `  ${mermaidId(node.id)}[\"${String(node.label).replaceAll('"', "'")}\"]`), ...data.edges.map(edge => `  ${mermaidId(edge.from)} -->${edge.label ? `|${String(edge.label).replaceAll("|", "/")}|` : ""} ${mermaidId(edge.to)}`)].join("\n");
  const markdown = `# ${data.title}\n\n## Architecture graph\n\n\`\`\`mermaid\n${mermaid}\n\`\`\`\n\n## Systems\n\n${[...groups.entries()].map(([group, nodes]) => `### ${group}\n${nodes.map(node => `- **${node.label}** (${node.kind ?? "component"}) — ${node.purpose} (${node.evidence.join(", ")})`).join("\n")}`).join("\n\n")}\n\n## Runtime flows\n\n${(data.flows ?? []).map(flow => `- **${flow.title}**: ${flow.summary} (${flow.steps.join(" → ")})`).join("\n") || "- None established."}\n\n## Recommendations\n\n${data.recommendations.map(item => `- **${item.title}** (${item.confidence}): ${item.why}. Validate: \`${item.safeValidationCommand}\``).join("\n")}\n`;
  const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escapeHtml(data.title)} | Architecture</title>
<style>
:root { color-scheme:light dark; --ink:oklch(24% .02 170); --paper:oklch(97% .012 90); --surface:oklch(99% .006 90); --wash:oklch(93% .025 170); --line:oklch(78% .025 170); --accent:oklch(43% .11 175); --muted:oklch(45% .025 170); --warm:oklch(67% .12 70); }
@media (prefers-color-scheme:dark) { :root { --ink:oklch(92% .015 170); --paper:oklch(18% .015 170); --surface:oklch(22% .018 170); --wash:oklch(28% .035 170); --line:oklch(39% .03 170); --accent:oklch(76% .1 175); --muted:oklch(73% .025 170); --warm:oklch(77% .11 70); } }
* { box-sizing:border-box; } body { margin:0; background:var(--paper); color:var(--ink); font:1rem/1.55 ui-sans-serif,system-ui,sans-serif; } button { font:inherit; } .skip-link { position:absolute; left:-999px; } .skip-link:focus { left:1rem; top:1rem; z-index:3; padding:.5rem .8rem; background:var(--surface); border:1px solid var(--line); } :where(button,a):focus-visible { outline:3px solid var(--warm); outline-offset:3px; }
.hero, main, footer { max-width:88rem; margin:auto; padding-inline:clamp(1rem,4vw,3rem); } .hero { padding-block:clamp(2.5rem,8vw,7rem) 2rem; border-bottom:1px solid var(--line); } .eyebrow { margin:0; color:var(--accent); font-size:.72rem; font-weight:750; letter-spacing:.12em; text-transform:uppercase; } h1 { max-width:16ch; margin:.35rem 0 .8rem; font-size:clamp(2.5rem,7vw,5.5rem); line-height:.92; letter-spacing:-.055em; } h2 { font-size:clamp(1.5rem,3vw,2.25rem); letter-spacing:-.03em; } h3 { margin:.15rem 0; font-size:1rem; } .lede { max-width:62ch; color:var(--muted); font-size:1.1rem; } main { padding-block:2rem 4rem; } .toolbar { display:flex; gap:.5rem; flex-wrap:wrap; margin:1rem 0 1.25rem; } .filter { border:1px solid var(--line); border-radius:999px; padding:.35rem .7rem; color:var(--ink); background:transparent; cursor:pointer; } .filter[aria-pressed="false"] { color:var(--muted); opacity:.55; }
.layout { display:grid; grid-template-columns:minmax(0,1fr) minmax(18rem,23rem); gap:1.25rem; align-items:start; } .map-canvas { position:relative; min-height:36rem; overflow:auto; padding:1rem; background:var(--surface); border:1px solid var(--line); } .connections { position:absolute; inset:0; width:100%; height:100%; pointer-events:none; z-index:0; } .connections line { stroke:var(--accent); stroke-opacity:.32; stroke-width:1.5; } .systems { position:relative; z-index:1; display:grid; gap:1rem; grid-template-columns:repeat(auto-fit,minmax(15rem,1fr)); } .system-group { min-width:15rem; border-top:3px solid var(--accent); background:var(--wash); padding:.8rem; transition:opacity .16s ease-out; } .system-group.is-muted { opacity:.2; } .system-group header { display:grid; grid-template-columns:1fr auto; gap:.1rem .5rem; align-items:baseline; margin-bottom:.8rem; } .system-group header .eyebrow { grid-column:1/-1; } .system-group header span { color:var(--muted); font-size:.78rem; } .node-stack { display:grid; gap:.5rem; } .graph-node { width:100%; text-align:left; border:1px solid var(--line); background:var(--surface); color:var(--ink); padding:.7rem; cursor:pointer; } .graph-node[aria-pressed="true"] { border-color:var(--accent); box-shadow:0 0 0 2px var(--accent); } .node-kind { display:block; color:var(--accent); font-size:.7rem; font-weight:700; letter-spacing:.08em; text-transform:uppercase; } .node-purpose { display:block; margin-top:.3rem; color:var(--muted); font-size:.84rem; line-height:1.35; } .inspector { position:sticky; top:1rem; padding:1.1rem; background:var(--surface); border:1px solid var(--line); } .inspector h2 { margin-top:0; font-size:1.15rem; } .inspector code, .recommendation code { display:block; overflow-wrap:anywhere; white-space:pre-wrap; padding:.55rem; background:var(--wash); font-size:.8rem; } .muted { color:var(--muted); } .evidence { padding-left:1.1rem; } .below { display:grid; grid-template-columns:1fr 1fr; gap:2rem; margin-top:3rem; } .flow { border-top:1px solid var(--line); padding:.8rem 0; } .flow p { color:var(--muted); } .flow ol { display:flex; flex-wrap:wrap; gap:.45rem; padding:0; list-style-position:inside; } .flow button { border:0; border-bottom:1px solid var(--accent); background:transparent; color:var(--ink); cursor:pointer; padding:0; } .recommendation { display:grid; grid-template-columns:minmax(12rem,1fr) 1.5fr; gap:.75rem 1rem; border-top:1px solid var(--line); padding:1rem 0; } .recommendation code { grid-column:1/-1; } .recommendation p { margin:0; color:var(--muted); } .confidence { color:var(--accent); font-size:.72rem; font-weight:750; letter-spacing:.08em; text-transform:uppercase; } footer { border-top:1px solid var(--line); color:var(--muted); padding-block:1.2rem 2rem; font-size:.85rem; }
@media (max-width:64rem) { .layout,.below { grid-template-columns:1fr; } .inspector { position:static; } } @media (prefers-reduced-motion:reduce) { * { transition:none !important; } }
</style>
</head>
<body>
<a class="skip-link" href="#content">Skip to architecture map</a>
<header class="hero"><p class="eyebrow">Evidence-backed onboarding</p><h1>${escapeHtml(data.title)}</h1><p class="lede">A model-selected system map. Choose a component for source evidence; use filters to focus on one system. Connections show confirmed relationships, not inferred ownership.</p></header>
<main id="content" tabindex="-1"><section aria-labelledby="map-title"><p class="eyebrow">System map</p><h2 id="map-title">How this repository holds together</h2><nav class="toolbar" aria-label="Filter systems">${groupFilters}</nav><div class="layout"><div class="map-canvas"><svg class="connections" aria-hidden="true"><g></g></svg><div class="systems">${groupMarkup}</div></div><aside class="inspector" aria-labelledby="detail-title"><p class="eyebrow">Component detail</p><h2 id="detail-title">Select a component</h2><div id="detail" class="muted">Purpose, source evidence, and confirmed connections appear here.</div></aside></div></section><section class="below"><div><p class="eyebrow">Runtime flows</p><h2>Paths through system</h2>${flowMarkup}</div><div><p class="eyebrow">Recommendations</p><h2>Follow-up work</h2>${recommendations}</div></section></main>
<footer>Generated locally. Grouping is chosen for this repository, not imposed by template. Facts carry source evidence; recommendations stay separate.</footer>
<script type="application/json" id="graph-data">${graphData}</script>
<script>
const data = JSON.parse(document.getElementById('graph-data').textContent); const map = document.querySelector('.map-canvas'); const svg = document.querySelector('.connections'); const detail = document.getElementById('detail');
function showNode(id) { const node = data.nodes.find(item => item.id === id); if (!node) return; document.querySelectorAll('.graph-node').forEach(item => item.setAttribute('aria-pressed', String(item.dataset.node === id))); detail.replaceChildren(); const title=document.createElement('h3'); title.textContent=node.label; const kind=document.createElement('p'); kind.className='eyebrow'; kind.textContent=node.group + ' · ' + (node.kind || 'component'); const purpose=document.createElement('p'); purpose.textContent=node.purpose; const label=document.createElement('p'); label.textContent='Source evidence'; const list=document.createElement('ul'); list.className='evidence'; node.evidence.forEach(path => { const item=document.createElement('li'); const code=document.createElement('code'); code.textContent=path; item.append(code); list.append(item); }); const related=data.edges.filter(edge => edge.from===id || edge.to===id); const relation=document.createElement('p'); relation.textContent=related.length ? 'Confirmed relationships: ' + related.map(edge => (edge.from===id ? '→ ' + edge.to : edge.from + ' →')).join(', ') : 'No confirmed relationships recorded.'; detail.append(kind,title,purpose,label,list,relation); }
function drawEdges() { const bounds=map.getBoundingClientRect(); const group=svg.querySelector('g'); group.replaceChildren(); data.edges.forEach(edge => { const from=document.querySelector('[data-node="'+CSS.escape(edge.from)+'"]'); const to=document.querySelector('[data-node="'+CSS.escape(edge.to)+'"]'); if (!from || !to) return; const a=from.getBoundingClientRect(), b=to.getBoundingClientRect(); const line=document.createElementNS('http://www.w3.org/2000/svg','line'); line.setAttribute('x1',a.left+a.width/2-bounds.left+map.scrollLeft); line.setAttribute('y1',a.top+a.height/2-bounds.top+map.scrollTop); line.setAttribute('x2',b.left+b.width/2-bounds.left+map.scrollLeft); line.setAttribute('y2',b.top+b.height/2-bounds.top+map.scrollTop); if (edge.label) line.setAttribute('aria-label',edge.label); group.append(line); }); }
document.querySelectorAll('.graph-node').forEach(button => button.addEventListener('click', () => showNode(button.dataset.node))); document.querySelectorAll('[data-node-jump]').forEach(button => button.addEventListener('click', () => { const node=document.querySelector('[data-node="'+CSS.escape(button.dataset.nodeJump)+'"]'); node?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'center'}); showNode(button.dataset.nodeJump); })); document.querySelectorAll('.filter').forEach(button => button.addEventListener('click', () => { const active=button.getAttribute('aria-pressed')==='true'; button.setAttribute('aria-pressed',String(!active)); document.querySelectorAll('.system-group[data-group="'+CSS.escape(button.dataset.group)+'"]').forEach(group => group.classList.toggle('is-muted',active)); })); new ResizeObserver(drawEdges).observe(map); window.addEventListener('load',drawEdges); map.addEventListener('scroll',drawEdges);
</script>
</body></html>`;
  return { html, markdown };
}

if (process.argv[1] && import.meta.url === new URL(`file://${process.argv[1]}`).href) {
  const [inputPath, htmlPath, markdownPath] = process.argv.slice(2);
  if (!inputPath || !htmlPath || !markdownPath) throw new Error("Usage: onboarding-graph <input.json> <architecture.html> <architecture.md>");
  const output = renderGraph(JSON.parse(readFileSync(inputPath, "utf8")));
  writeFileSync(htmlPath, output.html);
  writeFileSync(markdownPath, output.markdown);
}
